# Generated by Django 4.2 on 2023-08-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.imagegallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('release', models.DateField()),
                ('trailer_url', models.URLField(blank=True)),
                ('type_2D', models.BooleanField()),
                ('type_3D', models.BooleanField()),
                ('type_IMAX', models.BooleanField()),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.imagegallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.cinema')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.imagegallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='image_seo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('time', models.DateTimeField()),
                ('type_3D', models.BooleanField()),
                ('type_DBOX', models.BooleanField()),
                ('VIP', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.hall')),
            ],
        ),
    ]
